# version: '3.8'

# services:
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
#     container_name: elasticsearch
#     environment:
#       - discovery.type=single-node
#       - xpack.security.enabled=false
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ports:
#       - "9200:9200"
#     volumes:
#       - ./es-data:/usr/share/elasticsearch/data
#     networks:
#       - metro-net

#   kibana:
#     image: docker.elastic.co/kibana/kibana:8.12.0
#     container_name: kibana
#     environment:
#       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#     ports:
#       - "5601:5601"
#     depends_on:
#       - elasticsearch
#     networks:
#       - metro-net

# networks:
#   metro-net:
#     driver: bridge




version: '3.8'

services:
  # ----------------------------
  # Node 1
  # ----------------------------
  es-node01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es-node01
    environment:
      - node.name=es-node01
      - cluster.name=metro-cluster
      - discovery.seed_hosts=es-node02,es-node03
      - cluster.initial_master_nodes=es-node01,es-node02,es-node03
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
    volumes:
      - ./es-data01:/usr/share/elasticsearch/data
    networks:
      - metro-net

  # ----------------------------
  # Node 2
  # ----------------------------
  es-node02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es-node02
    environment:
      - node.name=es-node02
      - cluster.name=metro-cluster
      - discovery.seed_hosts=es-node01,es-node03
      - cluster.initial_master_nodes=es-node01,es-node02,es-node03
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9201:9200"
    volumes:
      - ./es-data02:/usr/share/elasticsearch/data
    networks:
      - metro-net

  # ----------------------------
  # Node 3
  # ----------------------------
  es-node03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es-node03
    environment:
      - node.name=es-node03
      - cluster.name=metro-cluster
      - discovery.seed_hosts=es-node01,es-node02
      - cluster.initial_master_nodes=es-node01,es-node02,es-node03
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9202:9200"
    volumes:
      - ./es-data03:/usr/share/elasticsearch/data
    networks:
      - metro-net

  # ----------------------------
  # Kibana
  # ----------------------------
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=["http://es-node01:9200","http://es-node02:9200","http://es-node03:9200"]
    ports:
      - "5601:5601"
    depends_on:
      - es-node01
      - es-node02
      - es-node03
    networks:
      - metro-net

networks:
  metro-net:
    driver: bridge